apiVersion: apps/v1
kind: Deployment
metadata:
  name: josephbaruch-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: josephbaruch
  template:
    metadata:
      labels:
        app: josephbaruch
    spec:
      containers:
      - name: josephbaruch-container
        image: localhost:5000/josephbaruch.com:latest
        ports:
        - containerPort: 8084
